const sampleJobs = [
    { company: "Google", position: "Software Engineer", status: "Interviewing" },
    { company: "Amazon", position: "Backend Development Engineer", status: "Applied" },
    { company: "Netflix", position: "Full Stack Engineer", status: "Rejected" },
    { company: "Meta", position: "Frontend Developer", status: "Applied" },
    { company: "Apple", position: "Systems Engineer", status: "Interviewing" },
    { company: "Microsoft", position: "Software Development Engineer II", status: "Rejected" },
    { company: "Spotify", position: "Web Developer", status: "Offered" },
    { company: "Stripe", position: "API Engineer", status: "Interviewing" },
    { company: "Airbnb", position: "Software Engineer - Trust", status: "Applied" },
    { company: "Uber", position: "Backend Engineer", status: "Rejected" },
    { company: "Lyft", position: "Full Stack Developer", status: "Applied" },
    { company: "Tesla", position: "Software Engineer - Infotainment", status: "Interviewing" },
    { company: "IBM", position: "Cloud Native Developer", status: "Offered" },
    { company: "Oracle", position: "Database Engineer", status: "Rejected" },
    { company: "Atlassian", position: "Frontend Engineer", status: "Applied" },
    { company: "Slack", position: "Software Engineer", status: "Interviewing" },
    { company: "GitHub", position: "Developer Relations Engineer", status: "Applied" },
    { company: "GitLab", position: "Backend Engineer - Ruby", status: "Rejected" },
    { node: "Docker", company: "Docker", position: "Go Developer", status: "Applied" },
    { company: "Vercel", position: "React/Next.js Engineer", status: "Interviewing" },
    { company: "Netlify", position: "Frontend Developer", status: "Offered" },
    { company: "Cloudflare", position: "Systems Engineer", status: "Applied" },
    { company: "Coinbase", position: "Blockchain Engineer", status: "Rejected" },
    { company: "Robinhood", position: "Software Engineer", status: "Applied" },
    { company: "Plaid", position: "Integration Engineer", status: "Interviewing" },
    { company: "Dropbox", position: "Backend Software Engineer", status: "Applied" },
    { company: "Zoom", position: "Full Stack Engineer", status: "Rejected" },
    { company: "Shopify", position: "Developer - Core", status: "Offered" },
    { company: "Adobe", position: "Web UI Developer", status: "Applied" },
    { company: "Salesforce", position: "Software Engineering AMTS", status: "Interviewing" },
    { company: "Reddit", position: "Frontend Engineer", status: "Applied" },
    { company: "Discord", position: "Full Stack Developer", status: "Interviewing" },
    { company: "Twitch", position: "Video Engineering Developer", status: "Rejected" },
    { company: "Palantir", position: "Forward Deployed Software Engineer", status: "Applied" },
    { company: "Snowflake", position: "Software Engineer - Data", status: "Offered" },
    { company: "Databricks", position: "Backend Engineer", status: "Applied" },
    { company: "Canva", position: "Frontend Engineer", status: "Interviewing" },
    { company: "Figma", position: "Software Engineer - Editor", status: "Rejected" },
    { company: "Notion", position: "Full Stack Developer", status: "Applied" },
    { company: "ByteDance", position: "Software Engineer", status: "Interviewing" },
    { company: "Bloomberg", position: "C++ Software Engineer", status: "Applied" },
    { company: "Square", position: "Backend Developer", status: "Rejected" },
    { company: "Roku", position: "Software Engineer", status: "Applied" },
    { company: "Zillow", position: "Full Stack Engineer", status: "Interviewing" },
    { company: "DoorDash", position: "Software Engineer", status: "Offered" },
    { company: "Instacart", position: "Frontend Developer", status: "Applied" },
    { company: "Pinterest", position: "Web Engineer", status: "Rejected" },
    { company: "Snap", position: "Software Engineer", status: "Applied" },
    { company: "Asana", position: "Product Engineer", status: "Interviewing" },
    { company: "Duolingo", position: "Software Engineer - Learner State", status: "Applied" }
];

module.exports = { data: sampleJobs };